name: Deploy Prod

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: SSH to VM & Deploy PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ">>> Switching to prod project directory"
            cd /home/ubuntu/badlao-deployment/prod/badlao || exit 1

            echo ">>> Switching to root user"
            sudo su <<'EOF'
            set -e

            echo ">>> Pulling latest code from master branch"
            cd /home/ubuntu/badlao-deployment/prod/badlao
            git pull origin master

            echo ">>> Ensure shared docker network exists"
            docker network inspect badlao_backend >/dev/null 2>&1 || docker network create badlao_backend

            echo ">>> Bringing down existing PROD containers"
            docker compose -f docker-compose-prod.yml down

            echo ">>> Rebuilding & starting PROD containers"
            docker compose -f docker-compose-prod.yml up -d --build

            echo ">>> PROD deployment completed!"
            EOF
