name: Deploy Prod

on:
  push:
    branches:
      - prod

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: SSH to VM & Deploy PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ">>> Switching to prod project directory"
            cd /home/ubuntu/badlao-deployment/prod/badlao || exit 1

            echo ">>> Switching to root user"
            sudo su <<'EOF'

            echo ">>> Pulling latest code from PROD branch"
            git pull origin prod || exit 1

            echo ">>> Bringing down existing PROD containers"
            docker compose -f docker-compose-prod.yml down || exit 1

            echo ">>> Rebuilding & starting PROD containers"
            docker compose -f docker-compose-prod.yml up --build -d || exit 1

            echo ">>> PROD deployment completed!"
            EOF
